#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'Sensing'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 13

# The Active Message type associated with this message.
AM_TYPE = -1

class Sensing(tinyos.message.Message.Message):
    # Create a new Sensing of size 13.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=13):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <Sensing> \n"
        try:
            s += "  [seqno=0x%x]\n" % (self.get_seqno())
        except:
            pass
        try:
            s += "  [sender=0x%x]\n" % (self.get_sender())
        except:
            pass
        try:
            s += "  [humidity=0x%x]\n" % (self.get_humidity())
        except:
            pass
        try:
            s += "  [temperature=0x%x]\n" % (self.get_temperature())
        except:
            pass
        try:
            s += "  [lightPar=0x%x]\n" % (self.get_lightPar())
        except:
            pass
        try:
            s += "  [lightTsr=0x%x]\n" % (self.get_lightTsr())
        except:
            pass
        try:
            s += "  [switchState=0x%x]\n" % (self.get_switchState())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: seqno
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'seqno' is signed (False).
    #
    def isSigned_seqno(self):
        return False
    
    #
    # Return whether the field 'seqno' is an array (False).
    #
    def isArray_seqno(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'seqno'
    #
    def offset_seqno(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'seqno'
    #
    def offsetBits_seqno(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'seqno'
    #
    def get_seqno(self):
        return self.getUIntElement(self.offsetBits_seqno(), 16, 1)
    
    #
    # Set the value of the field 'seqno'
    #
    def set_seqno(self, value):
        self.setUIntElement(self.offsetBits_seqno(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'seqno'
    #
    def size_seqno(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'seqno'
    #
    def sizeBits_seqno(self):
        return 16
    
    #
    # Accessor methods for field: sender
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'sender' is signed (False).
    #
    def isSigned_sender(self):
        return False
    
    #
    # Return whether the field 'sender' is an array (False).
    #
    def isArray_sender(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sender'
    #
    def offset_sender(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'sender'
    #
    def offsetBits_sender(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'sender'
    #
    def get_sender(self):
        return self.getUIntElement(self.offsetBits_sender(), 16, 1)
    
    #
    # Set the value of the field 'sender'
    #
    def set_sender(self, value):
        self.setUIntElement(self.offsetBits_sender(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sender'
    #
    def size_sender(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'sender'
    #
    def sizeBits_sender(self):
        return 16
    
    #
    # Accessor methods for field: humidity
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'humidity' is signed (False).
    #
    def isSigned_humidity(self):
        return False
    
    #
    # Return whether the field 'humidity' is an array (False).
    #
    def isArray_humidity(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'humidity'
    #
    def offset_humidity(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'humidity'
    #
    def offsetBits_humidity(self):
        return 32
    
    #
    # Return the value (as a int) of the field 'humidity'
    #
    def get_humidity(self):
        return self.getUIntElement(self.offsetBits_humidity(), 16, 1)
    
    #
    # Set the value of the field 'humidity'
    #
    def set_humidity(self, value):
        self.setUIntElement(self.offsetBits_humidity(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'humidity'
    #
    def size_humidity(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'humidity'
    #
    def sizeBits_humidity(self):
        return 16
    
    #
    # Accessor methods for field: temperature
    #   Field type: int
    #   Offset (bits): 48
    #   Size (bits): 16
    #

    #
    # Return whether the field 'temperature' is signed (False).
    #
    def isSigned_temperature(self):
        return False
    
    #
    # Return whether the field 'temperature' is an array (False).
    #
    def isArray_temperature(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'temperature'
    #
    def offset_temperature(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'temperature'
    #
    def offsetBits_temperature(self):
        return 48
    
    #
    # Return the value (as a int) of the field 'temperature'
    #
    def get_temperature(self):
        return self.getUIntElement(self.offsetBits_temperature(), 16, 1)
    
    #
    # Set the value of the field 'temperature'
    #
    def set_temperature(self, value):
        self.setUIntElement(self.offsetBits_temperature(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'temperature'
    #
    def size_temperature(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'temperature'
    #
    def sizeBits_temperature(self):
        return 16
    
    #
    # Accessor methods for field: lightPar
    #   Field type: int
    #   Offset (bits): 64
    #   Size (bits): 16
    #

    #
    # Return whether the field 'lightPar' is signed (False).
    #
    def isSigned_lightPar(self):
        return False
    
    #
    # Return whether the field 'lightPar' is an array (False).
    #
    def isArray_lightPar(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'lightPar'
    #
    def offset_lightPar(self):
        return (64 / 8)
    
    #
    # Return the offset (in bits) of the field 'lightPar'
    #
    def offsetBits_lightPar(self):
        return 64
    
    #
    # Return the value (as a int) of the field 'lightPar'
    #
    def get_lightPar(self):
        return self.getUIntElement(self.offsetBits_lightPar(), 16, 1)
    
    #
    # Set the value of the field 'lightPar'
    #
    def set_lightPar(self, value):
        self.setUIntElement(self.offsetBits_lightPar(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'lightPar'
    #
    def size_lightPar(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'lightPar'
    #
    def sizeBits_lightPar(self):
        return 16
    
    #
    # Accessor methods for field: lightTsr
    #   Field type: int
    #   Offset (bits): 80
    #   Size (bits): 16
    #

    #
    # Return whether the field 'lightTsr' is signed (False).
    #
    def isSigned_lightTsr(self):
        return False
    
    #
    # Return whether the field 'lightTsr' is an array (False).
    #
    def isArray_lightTsr(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'lightTsr'
    #
    def offset_lightTsr(self):
        return (80 / 8)
    
    #
    # Return the offset (in bits) of the field 'lightTsr'
    #
    def offsetBits_lightTsr(self):
        return 80
    
    #
    # Return the value (as a int) of the field 'lightTsr'
    #
    def get_lightTsr(self):
        return self.getUIntElement(self.offsetBits_lightTsr(), 16, 1)
    
    #
    # Set the value of the field 'lightTsr'
    #
    def set_lightTsr(self, value):
        self.setUIntElement(self.offsetBits_lightTsr(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'lightTsr'
    #
    def size_lightTsr(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'lightTsr'
    #
    def sizeBits_lightTsr(self):
        return 16
    
    #
    # Accessor methods for field: switchState
    #   Field type: short
    #   Offset (bits): 96
    #   Size (bits): 8
    #

    #
    # Return whether the field 'switchState' is signed (False).
    #
    def isSigned_switchState(self):
        return False
    
    #
    # Return whether the field 'switchState' is an array (False).
    #
    def isArray_switchState(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'switchState'
    #
    def offset_switchState(self):
        return (96 / 8)
    
    #
    # Return the offset (in bits) of the field 'switchState'
    #
    def offsetBits_switchState(self):
        return 96
    
    #
    # Return the value (as a short) of the field 'switchState'
    #
    def get_switchState(self):
        return self.getUIntElement(self.offsetBits_switchState(), 8, 1)
    
    #
    # Set the value of the field 'switchState'
    #
    def set_switchState(self, value):
        self.setUIntElement(self.offsetBits_switchState(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'switchState'
    #
    def size_switchState(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'switchState'
    #
    def sizeBits_switchState(self):
        return 8
    
